name: Lint and Test

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.22.6"
          check-latest: false

      - name: Run revive (v1.10.0)
        run: |
          go install github.com/mgechev/revive@6becd540e4f864330381c0f2cd0cf05089aa8aa3
          revive -config revive.toml -formatter friendly ./...

      - name: Run staticcheck (v0.6.1)
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@b8ec13ce4d00445d75da053c47498e6f9ec5d7d6
          staticcheck ./...

      - name: Run govulncheck (v1.1.4)
        run: |
          go version
          go install golang.org/x/vuln/cmd/govulncheck@d1f380186385b4f64e00313f31743df8e4b89a77
          govulncheck ./...

      - name: Run go test
        run: go test -v ./...

      - name: Build Executables
        run: |
          go build ./cmd/jb-sw-realm
          go build ./cmd/tenant_log

      - name: Run go mod tidy
        run: go mod tidy && git diff --quiet
